version: "3"

services:
  #poke-react-app:

  #poke-spring-api:
  #depends_on:
  #- postgres-service

  postgres-service:
    image: postgres:alpine
    container_name: postgres-db
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
